insert into currency values(	'Afghani','AFN','971','2');
insert into currency values(	'Euro','EUR','978','2');
insert into currency values(	'US Dollar','USD','840','2');
insert into currency values(	'Lek','ALL','008','2');
insert into currency values(	'Algerian Dinar','DZD','012','2');
insert into currency values(	'Kwanza','AOA','973','2');
insert into currency values(	'East Caribbean Dollar','XCD','951','2');
insert into currency values(	'No universal currency','','','');
insert into currency values(	'Argentine Peso','ARS','032','2');
insert into currency values(	'Armenian Dram','AMD','051','2');
insert into currency values(	'Aruban Florin','AWG','533','2');
insert into currency values(	'Australian Dollar','AUD','036','2');
insert into currency values(	'Azerbaijanian Manat','AZN','944','2');
insert into currency values(	'Bahamian Dollar','BSD','044','2');
insert into currency values(	'Bahraini Dinar','BHD','048','3');
insert into currency values(	'Taka','BDT','050','2');
insert into currency values(	'Barbados Dollar','BBD','052','2');
insert into currency values(	'Belarussian Ruble','BYR','974','0');
insert into currency values(	'Belize Dollar','BZD','084','2');
insert into currency values(	'CFA Franc BCEAO','XOF','952','0');
insert into currency values(	'Bermudian Dollar','BMD','060','2');
insert into currency values(	'Ngultrum','BTN','064','2');
insert into currency values(	'Indian Rupee','INR','356','2');
insert into currency values(	'Boliviano','BOB','068','2');
insert into currency values(	'Mvdol','BOV','984','2');
insert into currency values(	'Convertible Mark','BAM','977','2');
insert into currency values(	'Pula','BWP','072','2');
insert into currency values(	'Norwegian Krone','NOK','578','2');
insert into currency values(	'Brazilian Real','BRL','986','2');
insert into currency values(	'Brunei Dollar','BND','096','2');
insert into currency values(	'Bulgarian Lev','BGN','975','2');
insert into currency values(	'Burundi Franc','BIF','108','0');
insert into currency values(	'Riel','KHR','116','2');
insert into currency values(	'CFA Franc BEAC','XAF','950','0');
insert into currency values(	'Canadian Dollar','CAD','124','2');
insert into currency values(	'Cabo Verde Escudo','CVE','132','2');
insert into currency values(	'Cayman Islands Dollar','KYD','136','2');
insert into currency values(	'Unidad de Fomento','CLF','990','4');
insert into currency values(	'Chilean Peso','CLP','152','0');
insert into currency values(	'Yuan Renminbi','CNY','156','2');
insert into currency values(	'Colombian Peso','COP','170','2');
insert into currency values(	'Unidad de Valor Real','COU','970','2');
insert into currency values(	'Comoro Franc','KMF','174','0');
insert into currency values(	'Congolese Franc','CDF','976','2');
insert into currency values(	'New Zealand Dollar','NZD','554','2');
insert into currency values(	'Costa Rican Colon','CRC','188','2');
insert into currency values(	'Croatian Kuna','HRK','191','2');
insert into currency values(	'Peso Convertible','CUC','931','2');
insert into currency values(	'Cuban Peso','CUP','192','2');
insert into currency values(	'Netherlands Antillean Guilder','ANG','532','2');
insert into currency values(	'Czech Koruna','CZK','203','2');
insert into currency values(	'Danish Krone','DKK','208','2');
insert into currency values(	'Djibouti Franc','DJF','262','0');
insert into currency values(	'Dominican Peso','DOP','214','2');
insert into currency values(	'Egyptian Pound','EGP','818','2');
insert into currency values(	'El Salvador Colon','SVC','222','2');
insert into currency values(	'Nakfa','ERN','232','2');
insert into currency values(	'Ethiopian Birr','ETB','230','2');
insert into currency values(	'Falkland Islands Pound','FKP','238','2');
insert into currency values(	'Fiji Dollar','FJD','242','2');
insert into currency values(	'CFP Franc','XPF','953','0');
insert into currency values(	'Dalasi','GMD','270','2');
insert into currency values(	'Lari','GEL','981','2');
insert into currency values(	'Ghana Cedi','GHS','936','2');
insert into currency values(	'Gibraltar Pound','GIP','292','2');
insert into currency values(	'Quetzal','GTQ','320','2');
insert into currency values(	'Pound Sterling','GBP','826','2');
insert into currency values(	'Guinea Franc','GNF','324','0');
insert into currency values(	'Guyana Dollar','GYD','328','2');
insert into currency values(	'Gourde','HTG','332','2');
insert into currency values(	'Lempira','HNL','340','2');
insert into currency values(	'Hong Kong Dollar','HKD','344','2');
insert into currency values(	'Forint','HUF','348','2');
insert into currency values(	'Iceland Krona','ISK','352','0');
insert into currency values(	'Rupiah','IDR','360','2');
insert into currency values(	'SDR (Special Drawing Right)','XDR','960','N.A.');
insert into currency values(	'Iranian Rial','IRR','364','2');
insert into currency values(	'Iraqi Dinar','IQD','368','3');
insert into currency values(	'New Israeli Sheqel','ILS','376','2');
insert into currency values(	'Jamaican Dollar','JMD','388','2');
insert into currency values(	'Yen','JPY','392','0');
insert into currency values(	'Jordanian Dinar','JOD','400','3');
insert into currency values(	'Tenge','KZT','398','2');
insert into currency values(	'Kenyan Shilling','KES','404','2');
insert into currency values(	'North Korean Won','KPW','408','2');
insert into currency values(	'Won','KRW','410','0');
insert into currency values(	'Kuwaiti Dinar','KWD','414','3');
insert into currency values(	'Som','KGS','417','2');
insert into currency values(	'Kip','LAK','418','2');
insert into currency values(	'Lebanese Pound','LBP','422','2');
insert into currency values(	'Loti','LSL','426','2');
insert into currency values(	'Rand','ZAR','710','2');
insert into currency values(	'Liberian Dollar','LRD','430','2');
insert into currency values(	'Libyan Dinar','LYD','434','3');
insert into currency values(	'Swiss Franc','CHF','756','2');
insert into currency values(	'Pataca','MOP','446','2');
insert into currency values(	'Denar','MKD','807','2');
insert into currency values(	'Malagasy Ariary','MGA','969','2');
insert into currency values(	'Kwacha','MWK','454','2');
insert into currency values(	'Malaysian Ringgit','MYR','458','2');
insert into currency values(	'Rufiyaa','MVR','462','2');
insert into currency values(	'Ouguiya','MRO','478','2');
insert into currency values(	'Mauritius Rupee','MUR','480','2');
insert into currency values(	'ADB Unit of Account','XUA','965','N.A.');
insert into currency values(	'Mexican Peso','MXN','484','2');
insert into currency values(	'Mexican Unidad de Inversion (UDI)','MXV','979','2');
insert into currency values(	'Moldovan Leu','MDL','498','2');
insert into currency values(	'Tugrik','MNT','496','2');
insert into currency values(	'Moroccan Dirham','MAD','504','2');
insert into currency values(	'Mozambique Metical','MZN','943','2');
insert into currency values(	'Kyat','MMK','104','2');
insert into currency values(	'Namibia Dollar','NAD','516','2');
insert into currency values(	'Nepalese Rupee','NPR','524','2');
insert into currency values(	'Cordoba Oro','NIO','558','2');
insert into currency values(	'Naira','NGN','566','2');
insert into currency values(	'Rial Omani','OMR','512','3');
insert into currency values(	'Pakistan Rupee','PKR','586','2');
insert into currency values(	'Balboa','PAB','590','2');
insert into currency values(	'Kina','PGK','598','2');
insert into currency values(	'Guarani','PYG','600','0');
insert into currency values(	'Nuevo Sol','PEN','604','2');
insert into currency values(	'Philippine Peso','PHP','608','2');
insert into currency values(	'Zloty','PLN','985','2');
insert into currency values(	'Qatari Rial','QAR','634','2');
insert into currency values(	'New Romanian Leu','RON','946','2');
insert into currency values(	'Russian Ruble','RUB','643','2');
insert into currency values(	'Rwanda Franc','RWF','646','0');
insert into currency values(	'Saint Helena Pound','SHP','654','2');
insert into currency values(	'Tala','WST','882','2');
insert into currency values(	'Dobra','STD','678','2');
insert into currency values(	'Saudi Riyal','SAR','682','2');
insert into currency values(	'Serbian Dinar','RSD','941','2');
insert into currency values(	'Seychelles Rupee','SCR','690','2');
insert into currency values(	'Leone','SLL','694','2');
insert into currency values(	'Singapore Dollar','SGD','702','2');
insert into currency values(	'Sucre','XSU','994','N.A.');
insert into currency values(	'Solomon Islands Dollar','SBD','090','2');
insert into currency values(	'Somali Shilling','SOS','706','2');
insert into currency values(	'South Sudanese Pound','SSP','728','2');
insert into currency values(	'Sri Lanka Rupee','LKR','144','2');
insert into currency values(	'Sudanese Pound','SDG','938','2');
insert into currency values(	'Surinam Dollar','SRD','968','2');
insert into currency values(	'Lilangeni','SZL','748','2');
insert into currency values(	'Swedish Krona','SEK','752','2');
insert into currency values(	'WIR Euro','CHE','947','2');
insert into currency values(	'WIR Franc','CHW','948','2');
insert into currency values(	'Syrian Pound','SYP','760','2');
insert into currency values(	'New Taiwan Dollar','TWD','901','2');
insert into currency values(	'Somoni','TJS','972','2');
insert into currency values(	'Tanzanian Shilling','TZS','834','2');
insert into currency values(	'Baht','THB','764','2');
insert into currency values(	'Pa’anga','TOP','776','2');
insert into currency values(	'Trinidad and Tobago Dollar','TTD','780','2');
insert into currency values(	'Tunisian Dinar','TND','788','3');
insert into currency values(	'Turkish Lira','TRY','949','2');
insert into currency values(	'Turkmenistan New Manat','TMT','934','2');
insert into currency values(	'Uganda Shilling','UGX','800','0');
insert into currency values(	'Hryvnia','UAH','980','2');
insert into currency values(	'UAE Dirham','AED','784','2');
insert into currency values(	'US Dollar (Next day)','USN','997','2');
insert into currency values(	'Uruguay Peso en Unidades Indexadas (URUIURUI)','UYI','940','0');
insert into currency values(	'Peso Uruguayo','UYU','858','2');
insert into currency values(	'Uzbekistan Sum','UZS','860','2');
insert into currency values(	'Vatu','VUV','548','0');
insert into currency values(	'Bolivar','VEF','937','2');
insert into currency values(	'Dong','VND','704','0');
insert into currency values(	'Yemeni Rial','YER','886','2');
insert into currency values(	'Zambian Kwacha','ZMW','967','2');
insert into currency values(	'Zimbabwe Dollar','ZWL','932','2');
insert into currency values(	'Bond Markets Unit European Composite Unit (EURCO)','XBA','955','N.A.');
insert into currency values(	'Bond Markets Unit European Monetary Unit (E.M.U.-6)','XBB','956','N.A.');
insert into currency values(	'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)','XBC','957','N.A.');
insert into currency values(	'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)','XBD','958','N.A.');
insert into currency values(	'Codes specifically reserved for testing purposes','XTS','963','N.A.');
insert into currency values(	'The codes assigned for transactions where no currency is involved','XXX','999','N.A.');
insert into currency values(	'Gold','XAU','959','N.A.');
insert into currency values(	'Palladium','XPD','964','N.A.');
insert into currency values(	'Platinum','XPT','962','N.A.');
insert into currency values(	'Silver','XAG','961','N.A.');

insert into entity values (	'AFGHANISTAN','AFN');
insert into entity values (	'ÅLAND ISLANDS','EUR');
insert into entity values (	'ALBANIA','ALL');
insert into entity values (	'ALGERIA','DZD');
insert into entity values (	'AMERICAN SAMOA','USD');
insert into entity values (	'ANDORRA','EUR');
insert into entity values (	'ANGOLA','AOA');
insert into entity values (	'ANGUILLA','XCD');
insert into entity values (	'ANTARCTICA','');
insert into entity values (	'ANTIGUA AND BARBUDA','XCD');
insert into entity values (	'ARGENTINA','ARS');
insert into entity values (	'ARMENIA','AMD');
insert into entity values (	'ARUBA','AWG');
insert into entity values (	'AUSTRALIA','AUD');
insert into entity values (	'AUSTRIA','EUR');
insert into entity values (	'AZERBAIJAN','AZN');
insert into entity values (	'BAHAMAS','BSD');
insert into entity values (	'BAHRAIN','BHD');
insert into entity values (	'BANGLADESH','BDT');
insert into entity values (	'BARBADOS','BBD');
insert into entity values (	'BELARUS','BYR');
insert into entity values (	'BELGIUM','EUR');
insert into entity values (	'BELIZE','BZD');
insert into entity values (	'BENIN','XOF');
insert into entity values (	'BERMUDA','BMD');
insert into entity values (	'BHUTAN','BTN');
insert into entity values (	'BHUTAN','INR');
insert into entity values (	'BOLIVIA, PLURINATIONAL STATE OF','BOB');
insert into entity values (	'BOLIVIA, PLURINATIONAL STATE OF','BOV');
insert into entity values (	'BONAIRE, SINT EUSTATIUS AND SABA','USD');
insert into entity values (	'BOSNIA AND HERZEGOVINA','BAM');
insert into entity values (	'BOTSWANA','BWP');
insert into entity values (	'BOUVET ISLAND','NOK');
insert into entity values (	'BRAZIL','BRL');
insert into entity values (	'BRITISH INDIAN OCEAN TERRITORY','USD');
insert into entity values (	'BRUNEI DARUSSALAM','BND');
insert into entity values (	'BULGARIA','BGN');
insert into entity values (	'BURKINA FASO','XOF');
insert into entity values (	'BURUNDI','BIF');
insert into entity values (	'CAMBODIA','KHR');
insert into entity values (	'CAMEROON','XAF');
insert into entity values (	'CANADA','CAD');
insert into entity values (	'CABO VERDE','CVE');
insert into entity values (	'CAYMAN ISLANDS','KYD');
insert into entity values (	'CENTRAL AFRICAN REPUBLIC','XAF');
insert into entity values (	'CHAD','XAF');
insert into entity values (	'CHILE','CLF');
insert into entity values (	'CHILE','CLP');
insert into entity values (	'CHINA','CNY');
insert into entity values (	'CHRISTMAS ISLAND','AUD');
insert into entity values (	'COCOS (KEELING) ISLANDS','AUD');
insert into entity values (	'COLOMBIA','COP');
insert into entity values (	'COLOMBIA','COU');
insert into entity values (	'COMOROS','KMF');
insert into entity values (	'CONGO','XAF');
insert into entity values (	'CONGO, DEMOCRATIC REPUBLIC OF THE ','CDF');
insert into entity values (	'COOK ISLANDS','NZD');
insert into entity values (	'COSTA RICA','CRC');
insert into entity values (	'CÔTE D''IVOIRE','XOF');
insert into entity values (	'CROATIA','HRK');
insert into entity values (	'CUBA','CUC');
insert into entity values (	'CUBA','CUP');
insert into entity values (	'CURAÇAO','ANG');
insert into entity values (	'CYPRUS','EUR');
insert into entity values (	'CZECH REPUBLIC','CZK');
insert into entity values (	'DENMARK','DKK');
insert into entity values (	'DJIBOUTI','DJF');
insert into entity values (	'DOMINICA','XCD');
insert into entity values (	'DOMINICAN REPUBLIC','DOP');
insert into entity values (	'ECUADOR','USD');
insert into entity values (	'EGYPT','EGP');
insert into entity values (	'EL SALVADOR','SVC');
insert into entity values (	'EL SALVADOR','USD');
insert into entity values (	'EQUATORIAL GUINEA','XAF');
insert into entity values (	'ERITREA','ERN');
insert into entity values (	'ESTONIA','EUR');
insert into entity values (	'ETHIOPIA','ETB');
insert into entity values (	'EUROPEAN UNION','EUR');
insert into entity values (	'FALKLAND ISLANDS (MALVINAS)','FKP');
insert into entity values (	'FAROE ISLANDS','DKK');
insert into entity values (	'FIJI','FJD');
insert into entity values (	'FINLAND','EUR');
insert into entity values (	'FRANCE','EUR');
insert into entity values (	'FRENCH GUIANA','EUR');
insert into entity values (	'FRENCH POLYNESIA','XPF');
insert into entity values (	'FRENCH SOUTHERN TERRITORIES','EUR');
insert into entity values (	'GABON','XAF');
insert into entity values (	'GAMBIA','GMD');
insert into entity values (	'GEORGIA','GEL');
insert into entity values (	'GERMANY','EUR');
insert into entity values (	'GHANA','GHS');
insert into entity values (	'GIBRALTAR','GIP');
insert into entity values (	'GREECE','EUR');
insert into entity values (	'GREENLAND','DKK');
insert into entity values (	'GRENADA','XCD');
insert into entity values (	'GUADELOUPE','EUR');
insert into entity values (	'GUAM','USD');
insert into entity values (	'GUATEMALA','GTQ');
insert into entity values (	'GUERNSEY','GBP');
insert into entity values (	'GUINEA','GNF');
insert into entity values (	'GUINEA-BISSAU','XOF');
insert into entity values (	'GUYANA','GYD');
insert into entity values (	'HAITI','HTG');
insert into entity values (	'HAITI','USD');
insert into entity values (	'HEARD ISLAND AND McDONALD ISLANDS','AUD');
insert into entity values (	'HOLY SEE (VATICAN CITY STATE)','EUR');
insert into entity values (	'HONDURAS','HNL');
insert into entity values (	'HONG KONG','HKD');
insert into entity values (	'HUNGARY','HUF');
insert into entity values (	'ICELAND','ISK');
insert into entity values (	'INDIA','INR');
insert into entity values (	'INDONESIA','IDR');
insert into entity values (	'INTERNATIONAL MONETARY FUND (IMF) ','XDR');
insert into entity values (	'IRAN, ISLAMIC REPUBLIC OF','IRR');
insert into entity values (	'IRAQ','IQD');
insert into entity values (	'IRELAND','EUR');
insert into entity values (	'ISLE OF MAN','GBP');
insert into entity values (	'ISRAEL','ILS');
insert into entity values (	'ITALY','EUR');
insert into entity values (	'JAMAICA','JMD');
insert into entity values (	'JAPAN','JPY');
insert into entity values (	'JERSEY','GBP');
insert into entity values (	'JORDAN','JOD');
insert into entity values (	'KAZAKHSTAN','KZT');
insert into entity values (	'KENYA','KES');
insert into entity values (	'KIRIBATI','AUD');
insert into entity values (	'KOREA, DEMOCRATIC PEOPLE’S REPUBLIC OF','KPW');
insert into entity values (	'KOREA, REPUBLIC OF','KRW');
insert into entity values (	'KUWAIT','KWD');
insert into entity values (	'KYRGYZSTAN','KGS');
insert into entity values (	'LAO PEOPLE’S DEMOCRATIC REPUBLIC','LAK');
insert into entity values (	'LATVIA','EUR');
insert into entity values (	'LEBANON','LBP');
insert into entity values (	'LESOTHO','LSL');
insert into entity values (	'LESOTHO','ZAR');
insert into entity values (	'LIBERIA','LRD');
insert into entity values (	'LIBYA','LYD');
insert into entity values (	'LIECHTENSTEIN','CHF');
insert into entity values (	'LITHUANIA','EUR');
insert into entity values (	'LUXEMBOURG','EUR');
insert into entity values (	'MACAO','MOP');
insert into entity values (	'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF','MKD');
insert into entity values (	'MADAGASCAR','MGA');
insert into entity values (	'MALAWI','MWK');
insert into entity values (	'MALAYSIA','MYR');
insert into entity values (	'MALDIVES','MVR');
insert into entity values (	'MALI','XOF');
insert into entity values (	'MALTA','EUR');
insert into entity values (	'MARSHALL ISLANDS','USD');
insert into entity values (	'MARTINIQUE','EUR');
insert into entity values (	'MAURITANIA','MRO');
insert into entity values (	'MAURITIUS','MUR');
insert into entity values (	'MAYOTTE','EUR');
insert into entity values (	'MEMBER COUNTRIES OF THE AFRICAN DEVELOPMENT BANK GROUP','XUA');
insert into entity values (	'MEXICO','MXN');
insert into entity values (	'MEXICO','MXV');
insert into entity values (	'MICRONESIA, FEDERATED STATES OF','USD');
insert into entity values (	'MOLDOVA, REPUBLIC OF','MDL');
insert into entity values (	'MONACO','EUR');
insert into entity values (	'MONGOLIA','MNT');
insert into entity values (	'MONTENEGRO','EUR');
insert into entity values (	'MONTSERRAT','XCD');
insert into entity values (	'MOROCCO','MAD');
insert into entity values (	'MOZAMBIQUE','MZN');
insert into entity values (	'MYANMAR','MMK');
insert into entity values (	'NAMIBIA','NAD');
insert into entity values (	'NAMIBIA','ZAR');
insert into entity values (	'NAURU','AUD');
insert into entity values (	'NEPAL','NPR');
insert into entity values (	'NETHERLANDS','EUR');
insert into entity values (	'NEW CALEDONIA','XPF');
insert into entity values (	'NEW ZEALAND','NZD');
insert into entity values (	'NICARAGUA','NIO');
insert into entity values (	'NIGER','XOF');
insert into entity values (	'NIGERIA','NGN');
insert into entity values (	'NIUE','NZD');
insert into entity values (	'NORFOLK ISLAND','AUD');
insert into entity values (	'NORTHERN MARIANA ISLANDS','USD');
insert into entity values (	'NORWAY','NOK');
insert into entity values (	'OMAN','OMR');
insert into entity values (	'PAKISTAN','PKR');
insert into entity values (	'PALAU','USD');
insert into entity values (	'PALESTINE, STATE OF','');
insert into entity values (	'PANAMA','PAB');
insert into entity values (	'PANAMA','USD');
insert into entity values (	'PAPUA NEW GUINEA','PGK');
insert into entity values (	'PARAGUAY','PYG');
insert into entity values (	'PERU','PEN');
insert into entity values (	'PHILIPPINES','PHP');
insert into entity values (	'PITCAIRN','NZD');
insert into entity values (	'POLAND','PLN');
insert into entity values (	'PORTUGAL','EUR');
insert into entity values (	'PUERTO RICO','USD');
insert into entity values (	'QATAR','QAR');
insert into entity values (	'RÉUNION','EUR');
insert into entity values (	'ROMANIA','RON');
insert into entity values (	'RUSSIAN FEDERATION','RUB');
insert into entity values (	'RWANDA','RWF');
insert into entity values (	'SAINT BARTHÉLEMY','EUR');
insert into entity values (	'SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA','SHP');
insert into entity values (	'SAINT KITTS AND NEVIS','XCD');
insert into entity values (	'SAINT LUCIA','XCD');
insert into entity values (	'SAINT MARTIN (FRENCH PART)','EUR');
insert into entity values (	'SAINT PIERRE AND MIQUELON','EUR');
insert into entity values (	'SAINT VINCENT AND THE GRENADINES','XCD');
insert into entity values (	'SAMOA','WST');
insert into entity values (	'SAN MARINO','EUR');
insert into entity values (	'SAO TOME AND PRINCIPE','STD');
insert into entity values (	'SAUDI ARABIA','SAR');
insert into entity values (	'SENEGAL','XOF');
insert into entity values (	'SERBIA','RSD');
insert into entity values (	'SEYCHELLES','SCR');
insert into entity values (	'SIERRA LEONE','SLL');
insert into entity values (	'SINGAPORE','SGD');
insert into entity values (	'SINT MAARTEN (DUTCH PART)','ANG');
insert into entity values (	'SISTEMA UNITARIO DE COMPENSACION REGIONAL DE PAGOS "SUCRE"','XSU');
insert into entity values (	'SLOVAKIA','EUR');
insert into entity values (	'SLOVENIA','EUR');
insert into entity values (	'SOLOMON ISLANDS','SBD');
insert into entity values (	'SOMALIA','SOS');
insert into entity values (	'SOUTH AFRICA','ZAR');
insert into entity values (	'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS','');
insert into entity values (	'SOUTH SUDAN','SSP');
insert into entity values (	'SPAIN','EUR');
insert into entity values (	'SRI LANKA','LKR');
insert into entity values (	'SUDAN','SDG');
insert into entity values (	'SURINAME','SRD');
insert into entity values (	'SVALBARD AND JAN MAYEN','NOK');
insert into entity values (	'SWAZILAND','SZL');
insert into entity values (	'SWEDEN','SEK');
insert into entity values (	'SWITZERLAND','CHE');
insert into entity values (	'SWITZERLAND','CHF');
insert into entity values (	'SWITZERLAND','CHW');
insert into entity values (	'SYRIAN ARAB REPUBLIC','SYP');
insert into entity values (	'TAIWAN, PROVINCE OF CHINA','TWD');
insert into entity values (	'TAJIKISTAN','TJS');
insert into entity values (	'TANZANIA, UNITED REPUBLIC OF','TZS');
insert into entity values (	'THAILAND','THB');
insert into entity values (	'TIMOR-LESTE','USD');
insert into entity values (	'TOGO','XOF');
insert into entity values (	'TOKELAU','NZD');
insert into entity values (	'TONGA','TOP');
insert into entity values (	'TRINIDAD AND TOBAGO','TTD');
insert into entity values (	'TUNISIA','TND');
insert into entity values (	'TURKEY','TRY');
insert into entity values (	'TURKMENISTAN','TMT');
insert into entity values (	'TURKS AND CAICOS ISLANDS','USD');
insert into entity values (	'TUVALU','AUD');
insert into entity values (	'UGANDA','UGX');
insert into entity values (	'UKRAINE','UAH');
insert into entity values (	'UNITED ARAB EMIRATES','AED');
insert into entity values (	'UNITED KINGDOM','GBP');
insert into entity values (	'UNITED STATES','USD');
insert into entity values (	'UNITED STATES','USN');
insert into entity values (	'UNITED STATES MINOR OUTLYING ISLANDS','USD');
insert into entity values (	'URUGUAY','UYI');
insert into entity values (	'URUGUAY','UYU');
insert into entity values (	'UZBEKISTAN','UZS');
insert into entity values (	'VANUATU','VUV');
insert into entity values (	'VENEZUELA, BOLIVARIAN REPUBLIC OF','VEF');
insert into entity values (	'VIET NAM','VND');
insert into entity values (	'VIRGIN ISLANDS (BRITISH)','USD');
insert into entity values (	'VIRGIN ISLANDS (U.S.)','USD');
insert into entity values (	'WALLIS AND FUTUNA','XPF');
insert into entity values (	'WESTERN SAHARA','MAD');
insert into entity values (	'YEMEN','YER');
insert into entity values (	'ZAMBIA','ZMW');
insert into entity values (	'ZIMBABWE','ZWL');
insert into entity values (	'ZZ01_Bond Markets Unit European_EURCO','XBA');
insert into entity values (	'ZZ02_Bond Markets Unit European_EMU-6','XBB');
insert into entity values (	'ZZ03_Bond Markets Unit European_EUA-9','XBC');
insert into entity values (	'ZZ04_Bond Markets Unit European_EUA-17','XBD');
insert into entity values (	'ZZ06_Testing_Code','XTS');
insert into entity values (	'ZZ07_No_Currency','XXX');
insert into entity values (	'ZZ08_Gold','XAU');
insert into entity values (	'ZZ09_Palladium','XPD');
insert into entity values (	'ZZ10_Platinum','XPT');
insert into entity values (	'ZZ11_Silver','XAG');
